### ISSUE TITLE
Aap chutiye hain kya?

### ISSUE THREAD

**Issue by locx** [anoopdixith/TheConstitutionOfIndia#4]
Constitution should be like updated codebase. All amendments should be like changes to a git repo. Philosophy hi fateli hai tumhaari.

Thoda padho git kaise use karte hain.

**Comment by anoopdixith** [comment]
Wait, let me understand what you're saying. 
"Constitution should be like updated codebase" - Correct.
"All amendments should be like changes to a git repo" - Correct.
That's what I've done! I'm not sure what exactly your point is.
Thanks for being so rude, though.

**Comment by captn3m0** [comment]
@locx Why so rude?

**Comment by BorderlessNomad** [comment]
@locx I don't see any PR from you here to fix this issues? Stop pointing fingers and start working; this is an opensource project start contributing now.

**Comment by Shashwatsh** [comment]
i think this issue should be closed

**Comment by anoopdixith** [comment]
Closing.

**Comment by knightsamar** [comment]
Reported for abuse.
